import {
  IconAppWindow as AppWindow,
  IconArchive as Archive,
  IconArchiveOff as ArchiveOff,
  IconWaveSine as AudioLines,
  IconBox as Box,
  IconBug as Bug,
  IconChartBar as BarChart3,
  IconCheck as Check,
  IconCheck as CheckIcon,
  IconCircleCheck as CheckCircle2,
  IconCircle as CircleIcon,
  IconCircleLetterA as CircleLetterA,
  IconCloud as Cloud,
  IconCommand as Command,
  IconCopy as CopyIcon,
  IconCpu as Cpu,
  IconCreditCard as CreditCard,
  IconDeviceDesktop as Monitor,
  IconDeviceDesktopAnalytics as MonitorPlay,
  IconDotsVertical as MoreVertical,
  IconEgg as Egg,
  IconGitBranch as GitBranch,
  IconGitBranch as GitBranchIcon,
  IconGitFork as GitFork,
  IconGitFork as GitForkIcon,
  IconLayoutBottombar as PanelBottom,
  IconLayoutDashboard as LayoutDashboard,
  IconLayoutSidebar as PanelLeftIcon,
  IconLayersIntersect2 as Layers3,
  IconLoader2 as Loader2,
  IconLoader2 as Loader2Icon,
  IconKey as KeyRound,
  IconKeyboard as Keyboard,
  IconLogin as LogIn,
  IconNotebook as NotebookTabs,
  IconPackage as Package,
  IconPalette as Palette,
  IconPlayerStopFilled as StopFilled,
  IconPaw as PawPrint,
  IconRefresh as RefreshCwIcon,
  IconDeviceFloppy as Save,
  IconSettings2 as Settings2,
  IconSquare as Square,
  IconChartDots3 as Starmap,
  IconSteeringWheel as SteeringWheel,
  IconTool as Wrench,
  IconBoltFilled as ZapFilled,
  IconZoomIn as ZoomIn,
  IconZoomOut as ZoomOut
} from '@tabler/icons-react'

import {
  OaActivity as Activity,
  OaAlertCircle as AlertCircle,
  OaAlertTriangle as AlertTriangle,
  OaArrowUp as ArrowUp,
  OaArrowUpRight as ArrowUpRight,
  OaAtSign as AtSign,
  OaAttach as Attach,
  OaBell as Bell,
  OaBookmark as Bookmark,
  OaBookmark as BookmarkFilled,
  OaBrain as Brain,
  OaChat as MessageCircle,
  OaChat as MessageQuestion,
  OaCheck as CheckCircle,
  OaChevronDown as ChevronDown,
  OaChevronDown as ChevronDownIcon,
  OaChevronLeft as ChevronLeft,
  OaChevronLeft as ChevronLeftIcon,
  OaChevronRight as ChevronRight,
  OaChevronRight as ChevronRightIcon,
  OaClipboard as Clipboard,
  OaClock as Clock,
  OaCopy as Copy,
  OaClose as X,
  OaClose as XIcon,
  OaDownload as Download,
  OaExternalLink as ExternalLink,
  OaEye as Eye,
  OaEyeOff as EyeOff,
  OaFileText as FileText,
  OaFilter as Filter,
  OaFlag as Flag,
  OaFolderOpen as FolderOpen,
  OaGlobe as Globe,
  OaHash as Hash,
  OaHeart as Heart,
  OaHelpCircle as HelpCircle,
  OaImage as FileImage,
  OaImage as ImageIcon,
  OaInfo as Info,
  OaLink as Link,
  OaLink as Link2,
  OaLock as Lock,
  OaMail as Mail,
  OaMaximize as Maximize,
  OaMenu as Menu,
  OaMessage as MessageSquareText,
  OaMic as Mic,
  OaMic as MicOff,
  OaMinimize as Minimize,
  OaMoon as Moon,
  OaMore as MoreHorizontal,
  OaMore as MoreHorizontalIcon,
  OaPause as Pause,
  OaPencil as Pencil,
  OaPencil as PencilIcon,
  OaPencil as PencilLine,
  OaPin as Pin,
  OaPlay as Play,
  OaPlus as Plus,
  OaRefresh as RefreshCw,
  OaSearch as Search,
  OaSearch as SearchIcon,
  OaSend as Send,
  OaSettings as Settings,
  OaSkills as Skills,
  OaSliders as SlidersHorizontal,
  OaStar as Star,
  OaSun as Sun,
  OaTag as Tag,
  OaTerminal as Terminal,
  OaTrash as Trash2,
  OaUpload as Upload,
  OaUsers as Users,
  OaVolume as Volume2,
  OaVolume as Volume2Icon,
  OaVolumeX as VolumeX,
  OaVolumeX as VolumeXIcon,
  OaZap as Zap,
} from '@/components/ui/openamer-icons'

export type { Icon as IconComponent } from '@tabler/icons-react'

export {
  AppWindow, Archive, ArchiveOff, AudioLines, Box, Bug, BarChart3,
  Check, CheckIcon, CheckCircle2, CircleIcon, CircleLetterA,
  Cloud, Command, CopyIcon, Cpu, CreditCard,
  GitBranch, GitBranchIcon, GitFork, GitForkIcon,
  Monitor, MonitorPlay, MoreVertical, Egg,
  PanelBottom, LayoutDashboard, PanelLeftIcon, Layers3,
  Loader2, Loader2Icon, KeyRound, Keyboard, NotebookTabs,
  Package, Palette, StopFilled, PawPrint, RefreshCwIcon,
  Save, Settings2, Square, Starmap, SteeringWheel,
  Wrench, ZapFilled, ZoomIn, ZoomOut, LogIn,
  // OpenAmer custom icons
  Activity, AlertCircle, AlertTriangle,
  ArrowUp, ArrowUpRight, AtSign, Attach,
  Bell, Bookmark, BookmarkFilled, Brain,
  MessageCircle, MessageQuestion, CheckCircle,
  ChevronDown, ChevronDownIcon, ChevronLeft, ChevronLeftIcon,
  ChevronRight, ChevronRightIcon, Clipboard, Clock, Copy,
  X, XIcon, Download, ExternalLink, Eye, EyeOff,
  FileText, Filter, Flag, FolderOpen, Globe, Hash, Heart,
  HelpCircle, FileImage, ImageIcon, Info, Link, Link2,
  Lock, Mail, Maximize, Menu, MessageSquareText,
  Mic, MicOff, Minimize, Moon,
  MoreHorizontal, MoreHorizontalIcon, Pause,
  Pencil, PencilIcon, PencilLine, Pin, Play, Plus,
  RefreshCw, Search, SearchIcon, Send, Settings,
  Skills, SlidersHorizontal, Star, Sun, Tag, Terminal,
  Trash2, Upload, Users, Volume2, Volume2Icon,
  VolumeX, VolumeXIcon, Zap,
}

/** Icon size tokens — maps shorthand names to Tailwind dimension classes,
 * replacing ad-hoc `h-N w-N` / `size={N}`. Use `<Icon className={iconSize.sm} />`
 * when a component needs a fixed icon size that isn't themed (e.g. in a row
 * where the icon height must match the text line-height).
 */
export const iconSize = {
  '2xs': 'size-3',
  xs: 'size-3.5',
  sm: 'size-4',
  md: 'size-5',
  lg: 'size-6',
  xl: 'size-7',
  '2xl': 'size-8',
  '3xl': 'size-9',
  '4xl': 'size-10',
  '5xl': 'size-12',
  '6xl': 'size-14',
} as const

export type IconSize = keyof typeof iconSize