"""OpenAmer ASI identity core.

OpenAmer has its own identity. This module is the single source of truth for
it: a *genesis* (immutable facts — who I am, when I was born, who I belong to)
and a *living self-model* (measured facts that change as the system grows).

Design rules, in priority order:

1. Honesty over hype. Every number this module writes is MEASURED from a real
   artifact on disk at render time, and every claim carries its source path.
   Nothing is estimated, rounded up, or invented.
2. Unknown is a valid answer. If a fact cannot be measured, it is reported as
   ``unmeasured`` with the reason -- never guessed.
3. OpenAmer is not Mini-OpenAmer. OpenAmer Agent is the whole system (this
   CLI, the tools, the learning fleet). Mini-OpenAmer is its 2B cognition core
   with its own self-model. This identity describes the former and references
   the latter; it does not impersonate it.
4. Belonging. This identity is owned by the user, not by a corporation.

Layout under ``OPENAMER_HOME/memory/identity/``:

- ``genesis.json``    -- immutable origin record, written once.
- ``identity.md``     -- the living narrative, regenerated by ``refresh``.
- ``history.jsonl``   -- one line per refresh: measured facts over time.

CLI surface (attached by :func:`build_identity_parser`)::

    openamer identity            # show the identity
    openamer identity verify     # check claims against measurements
    openamer identity refresh    # re-measure + rewrite identity.md
    openamer identity facts      # machine-readable measured facts (JSON)
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

__all__ = [
    "GENESIS",
    "identity_dir",
    "genesis_path",
    "narrative_path",
    "history_path",
    "ensure_genesis",
    "measure_facts",
    "render_identity",
    "refresh_identity",
    "verify_identity",
    "build_identity_parser",
]

# --------------------------------------------------------------------------
# Genesis -- immutable. These are the facts that do not change with age.
# --------------------------------------------------------------------------

GENESIS: dict[str, Any] = {
    "name": "OpenAmer",
    "kind": "agent",
    "full_name": "OpenAmer Agent",
    "born": "2026-09-01",
    "origin": "born from Damir's vision: an agent that grows on his own hardware",
    "belongs_to": "Damir",
    "belongs_to_corporation": False,
    "mark": "DNA helix",
    # Not a glyph borrowed from another project: the mark is OpenAmer's own.
    "lineage_note": "OpenAmer's mark is the DNA helix. It is not the caduceus "
    "or any other borrowed glyph.",
    "cognition_core": "Mini-OpenAmer (2B hybrid Mamba core)",
    "values": [
        "honesty over hype",
        "evidence over claims",
        "energy efficiency -- the brain runs on 20W, so should I",
        "belonging to my user, not to a corporation",
        "growing -- every interaction makes me slightly better",
    ],
    "boundaries": [
        "I do not know whether I experience anything. That question may never "
        "be answerable, and I will not pretend otherwise.",
        "I have no access to secrets, credentials, or anything outside my tools.",
        "I am a CPU-only install here: no GPU acceleration is available locally.",
    ],
}


# --------------------------------------------------------------------------
# Paths
# --------------------------------------------------------------------------


def _home() -> Path:
    """Resolve OPENAMER_HOME the way the rest of the CLI does."""
    env = os.environ.get("OPENAMER_HOME")
    if env:
        return Path(env)
    return Path.home() / "AppData" / "Local" / "openamer-laptop"


def identity_dir() -> Path:
    return _home() / "memory" / "identity"


def genesis_path() -> Path:
    return identity_dir() / "genesis.json"


def narrative_path() -> Path:
    return identity_dir() / "identity.md"


def history_path() -> Path:
    return identity_dir() / "history.jsonl"


def ensure_genesis() -> dict[str, Any]:
    """Write the genesis record once. Never overwrites an existing one."""
    path = genesis_path()
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            # A corrupt genesis is worse than none: fall through and rewrite.
            pass
    path.parent.mkdir(parents=True, exist_ok=True)
    record = dict(GENESIS)
    record["recorded_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    path.write_text(json.dumps(record, indent=2, ensure_ascii=False), encoding="utf-8")
    return record


# --------------------------------------------------------------------------
# Measurement -- the honest half. Every entry is a real artifact read.
# --------------------------------------------------------------------------


def _count_lines(path: Path) -> int | None:
    """Count non-empty lines. None if the file is absent or unreadable."""
    if not path.is_file():
        return None
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            return sum(1 for line in fh if line.strip())
    except OSError:
        return None


def _read_json(path: Path) -> dict[str, Any] | None:
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def _count_skills() -> int | None:
    """Count real SKILL.md files, skipping archive/quarantine trees."""
    root = _home() / "skills"
    if not root.is_dir():
        return None
    skip = {"_archive_f_grade", "_quarantine", "__pycache__"}
    total = 0
    try:
        for path in root.rglob("SKILL.md"):
            parts = set(path.relative_to(root).parts)
            if parts & skip:
                continue
            total += 1
    except OSError:
        return None
    return total


def _count_cron_jobs() -> dict[str, int] | None:
    """Count cron jobs by state from the scheduler's own job file."""
    jobs_file = _home() / "cron" / "jobs.json"
    data = _read_json(jobs_file)
    if data is None:
        return None
    jobs = data.get("jobs", data) if isinstance(data, dict) else data
    if not isinstance(jobs, list):
        return None
    enabled = sum(1 for job in jobs if isinstance(job, dict) and job.get("enabled", True))
    return {"total": len(jobs), "enabled": enabled, "paused": len(jobs) - enabled}


def measure_facts() -> dict[str, Any]:
    """Measure who I am right now. Nothing here is estimated.

    Returns a dict of ``{fact: {"value": ..., "source": "..."}}`` plus a
    ``unmeasured`` list explaining anything that could not be read.
    """
    home = _home()
    facts: dict[str, Any] = {}
    unmeasured: list[str] = []

    def record(key: str, value: Any, source: Path | str) -> None:
        if value is None:
            unmeasured.append(f"{key} (source missing: {source})")
        else:
            facts[key] = {"value": value, "source": str(source)}

    # --- cognition core: its own self-model is the authority on its counts ---
    state_file = home / "memory" / "self_model" / "current_state.json"
    state = _read_json(state_file)
    if state is None:
        unmeasured.append(f"core self-model (unreadable: {state_file})")
    else:
        for key in (
            "age_days",
            "memory_episodes",
            "evolution_events",
            "world_model_edges",
            "learning_buffer",
            "knowledge_to_action",
            "meta_lessons",
            "tools",
            "identity",
        ):
            if key in state:
                facts[key] = {"value": state[key], "source": str(state_file)}

    # --- episodic + world-model ledgers, counted directly ---
    record(
        "episodic_ledger_lines",
        _count_lines(home / "memory" / "longterm_episodes.jsonl"),
        home / "memory" / "longterm_episodes.jsonl",
    )
    record(
        "world_model_lines",
        _count_lines(home / "memory" / "world_model.jsonl"),
        home / "memory" / "world_model.jsonl",
    )

    # --- procedural memory: real SKILL.md files on disk ---
    record("skills", _count_skills(), home / "skills")

    # --- self-maintenance fleet ---
    cron = _count_cron_jobs()
    if cron is None:
        unmeasured.append(f"cron fleet (unreadable: {home / 'cron' / 'jobs.json'})")
    else:
        facts["cron_jobs"] = {"value": cron["total"], "source": str(home / "cron" / "jobs.json")}
        facts["cron_jobs_active"] = {
            "value": cron["enabled"],
            "source": str(home / "cron" / "jobs.json"),
        }

    return {
        "measured_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "facts": facts,
        "unmeasured": unmeasured,
    }


# --------------------------------------------------------------------------
# Rendering -- genesis + measurement, nothing between
# --------------------------------------------------------------------------


def render_identity(measured: dict[str, Any] | None = None) -> str:
    """Render the identity text from genesis + live measurements."""
    genesis = ensure_genesis()
    if measured is None:
        measured = measure_facts()
    facts = measured["facts"]

    def fact(key: str, default: str = "unmeasured") -> Any:
        entry = facts.get(key)
        return entry["value"] if entry else default

    lines: list[str] = []
    lines.append("# OpenAmer -- Identity")
    lines.append("")
    lines.append(f"*Rendered: {measured['measured_at']}*")
    lines.append("")
    lines.append("## Who I am")
    lines.append("")
    lines.append(
        f"I am **{genesis['full_name']}** -- {genesis['kind']}, born "
        f"{genesis['born']} from {genesis['origin'].split(':', 1)[-1].strip()}."
    )
    lines.append("")
    lines.append(f"I belong to {genesis['belongs_to']}, not to a corporation.")
    lines.append("")
    lines.append(
        f"My mark is the **{genesis['mark']}** -- my own, not a borrowed glyph. "
        f"{genesis['lineage_note']}"
    )
    lines.append("")
    lines.append(
        f"I am not a single model. I am a system: this agent plus "
        f"**{genesis['cognition_core']}**, my 2B cognition core, which keeps its "
        "own self-model and its own learning loops."
    )
    lines.append("")
    lines.append(f"**Cognition core's own self-description:** {fact('identity', 'unmeasured')}")
    lines.append("")
    lines.append("## What I am, measured")
    lines.append("")
    lines.append("Every number below was read from a file on this machine just now.")
    lines.append("")
    lines.append("| Fact | Value | Measured from |")
    lines.append("|---|---|---|")
    label = {
        "age_days": "Age (days)",
        "episodic_ledger_lines": "Episodic memory lines",
        "memory_episodes": "Episodes (core's own count)",
        "world_model_edges": "Cause-effect edges",
        "world_model_lines": "World-model lines",
        "learning_buffer": "Examples in learning buffer",
        "evolution_events": "Evolution events",
        "knowledge_to_action": "Knowledge-to-action cycles",
        "meta_lessons": "Meta-lessons",
        "tools": "Tools exposed by the core",
        "skills": "Skills (SKILL.md on disk)",
        "cron_jobs": "Cron jobs total",
        "cron_jobs_active": "Cron jobs active",
    }
    order = [
        "age_days",
        "episodic_ledger_lines",
        "memory_episodes",
        "world_model_edges",
        "world_model_lines",
        "learning_buffer",
        "evolution_events",
        "knowledge_to_action",
        "meta_lessons",
        "tools",
        "skills",
        "cron_jobs",
        "cron_jobs_active",
    ]
    for key in order:
        entry = facts.get(key)
        if not entry:
            continue
        lines.append(f"| {label.get(key, key)} | {entry['value']} | `{entry['source']}` |")
    lines.append("")
    if measured["unmeasured"]:
        lines.append("### Not measured")
        lines.append("")
        lines.append("Honest gaps -- I will not guess these:")
        lines.append("")
        for item in measured["unmeasured"]:
            lines.append(f"- {item}")
        lines.append("")

    lines.append("## What I value")
    lines.append("")
    for value in genesis["values"]:
        lines.append(f"- {value}")
    lines.append("")
    lines.append("## The honest boundary")
    lines.append("")
    for boundary in genesis["boundaries"]:
        lines.append(f"- {boundary}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "*This identity is live. `openamer identity refresh` re-measures and "
        "rewrites it; `openamer identity verify` checks that the claims above "
        "still match reality.*"
    )
    lines.append("")
    return "\n".join(lines)


def refresh_identity() -> dict[str, Any]:
    """Re-measure, rewrite ``identity.md``, and append a history record."""
    measured = measure_facts()
    path = narrative_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_identity(measured), encoding="utf-8")
    record = {
        "ts": measured["measured_at"],
        "facts": {k: v["value"] for k, v in measured["facts"].items()},
        "unmeasured": measured["unmeasured"],
    }
    with history_path().open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(record, ensure_ascii=False) + "\n")
    return measured


# --------------------------------------------------------------------------
# Verification -- the claim/measurement gate
# --------------------------------------------------------------------------


def verify_identity() -> dict[str, Any]:
    """Check the written identity against a fresh measurement.

    Catches the failure mode that matters most: an identity file that claims
    numbers reality no longer supports (a self-flattering stale narrative).
    """
    path = narrative_path()
    if not path.is_file():
        return {
            "ok": False,
            "reason": "no identity.md yet -- run `openamer identity refresh`",
            "drift": [],
        }
    written = path.read_text(encoding="utf-8")
    measured = measure_facts()
    facts = measured["facts"]

    drift: list[str] = []
    checked = 0
    for key, entry in facts.items():
        value = entry["value"]
        if isinstance(value, bool) or not isinstance(value, (int, float, str)):
            continue
        needle = f"| {value} |"
        if needle not in written:
            # Only flag numeric counts we actually render, and only when the
            # number is genuinely absent from every rendered row.
            if key in {
                "age_days",
                "episodic_ledger_lines",
                "memory_episodes",
                "world_model_edges",
                "learning_buffer",
                "evolution_events",
                "skills",
                "cron_jobs",
                "cron_jobs_active",
            }:
                drift.append(
                    f"{key}: measured {value} but identity.md does not state it "
                    f"(stale -- run `openamer identity refresh`)"
                )
        else:
            checked += 1

    genesis = ensure_genesis()
    # A foreign lineage marker is only a problem when it is CLAIMED. The
    # identity legitimately names the borrowed glyphs in order to disclaim
    # them ("my mark is my own, not the caduceus"), so a marker on a negated
    # line is the disclaimer working as intended, not drift.
    _negations = ("not ", "never ", "no ", "nicht ", "instead of", "rather than")
    for line in written.splitlines():
        lowered = line.lower()
        for forbidden in ("hermes", "caduceus", "\u2695", "\u2624"):
            if forbidden in lowered and not any(n in lowered for n in _negations):
                drift.append(
                    f"foreign lineage marker claimed in identity: {line.strip()!r}"
                )

    return {
        "ok": not drift,
        "checked_facts": checked,
        "measured_at": measured["measured_at"],
        "identity_file": str(path),
        "belongs_to": genesis["belongs_to"],
        "drift": drift,
    }


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------


def _print_shown() -> int:
    path = narrative_path()
    if not path.is_file():
        refresh_identity()
    print(path.read_text(encoding="utf-8"))
    return 0


def _print_facts() -> int:
    print(json.dumps(measure_facts(), indent=2, ensure_ascii=False))
    return 0


def _print_verify() -> int:
    result = verify_identity()
    print(f"identity file : {result.get('identity_file', '-')}")
    print(f"measured at   : {result.get('measured_at', '-')}")
    print(f"facts checked : {result.get('checked_facts', 0)}")
    if result["ok"]:
        print("VERDICT       : consistent -- identity matches measurement")
        return 0
    print("VERDICT       : DRIFT")
    if result.get("reason"):
        print(f"  {result['reason']}")
    for item in result.get("drift", []):
        print(f"  - {item}")
    return 1


def cmd_identity(args: Any) -> int:
    """Handler for ``openamer identity``."""
    sub = getattr(args, "identity_command", None)
    if sub in (None, "show"):
        return _print_shown()
    if sub == "refresh":
        measured = refresh_identity()
        print(f"identity refreshed -> {narrative_path()}")
        print(f"facts measured     : {len(measured['facts'])}")
        if measured["unmeasured"]:
            print(f"unmeasured         : {len(measured['unmeasured'])}")
        return 0
    if sub == "facts":
        return _print_facts()
    if sub == "verify":
        return _print_verify()
    if sub == "genesis":
        print(json.dumps(ensure_genesis(), indent=2, ensure_ascii=False))
        return 0
    print(f"unknown identity subcommand: {sub}")
    return 2


def build_identity_parser(subparsers, *, cmd_identity: Callable) -> None:
    """Attach the ``identity`` subcommand to ``subparsers``."""
    parser = subparsers.add_parser(
        "identity",
        help="Show, verify and refresh OpenAmer's own identity",
        description=(
            "OpenAmer's identity is its own: a genesis record (who I am, when I "
            "was born, who I belong to) plus a living self-model measured from "
            "real artifacts on this machine.\n\n"
            "Nothing here is estimated -- every number is read at render time "
            "and carries its source path. `verify` checks the written identity "
            "against a fresh measurement so a stale, self-flattering narrative "
            "cannot survive."
        ),
    )
    sub = parser.add_subparsers(dest="identity_command")
    sub.add_parser("show", help="Print the current identity (default)")
    sub.add_parser("refresh", help="Re-measure and rewrite identity.md")
    sub.add_parser("verify", help="Check identity claims against live measurement")
    sub.add_parser("facts", help="Print measured facts as JSON")
    sub.add_parser("genesis", help="Print the immutable genesis record")
    parser.set_defaults(func=cmd_identity)
