#!/usr/bin/env python3
"""
Weekly Darwin evolution report -> GitHub issue (or local file fallback).
Usage:
  python darwin_weekly_report.py            # writes reports/darwin-weekly.md
  python darwin_weekly_report.py --post     # + posts to GitHub via gh CLI
"""
import json
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts"))

import importlib.util
spec = importlib.util.spec_from_file_location(
    "darwin_engine", REPO / "scripts" / "darwin_engine.py")
darwin = importlib.util.module_from_spec(spec)
sys.modules["darwin_engine"] = darwin
spec.loader.exec_module(darwin)

WEEKLY_FILE = Path("reports") / "darwin-weekly.md"


def build_weekly() -> str:
    s = darwin.status_overview()
    trend = darwin.fitness_trend()
    week_ago = datetime.now(timezone.utc) - timedelta(days=7)
    # fitness delta over the week from history
    deltas = []
    if darwin.HISTORY_FILE.exists():
        entries = [json.loads(l) for l in
                   open(darwin.HISTORY_FILE, encoding="utf-8") if l.strip()]
        week = [e for e in entries
                if datetime.fromisoformat(e["when"]) >= week_ago]
        if len(week) >= 2:
            first, last = week[0]["skills"], week[-1]["skills"]
            for name in last:
                if name in first and first[name] != last[name]:
                    deltas.append((name, round(last[name] - first[name], 2)))
            deltas.sort(key=lambda kv: kv[1], reverse=True)

    lines = [
        "# 🧬 Darwin Weekly Evolution Report",
        f"_{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_",
        "",
        f"**Population:** {s['population']} skills | **Trend:** {s['trend']}",
        f"**Fittest:** `{s['fittest']}` | **Weakest:** `{s['weakest']}`",
        f"**Species:** {s['species']['installed']} installed, "
        f"{s['species']['candidate']} candidates, {s['species']['retired']} retired",
        f"**Active trials:** {s['active_trials']} | "
        f"**Harvested ideas:** {s['harvested_blueprints']}",
        "",
        "## Biggest fitness movers (7 days)",
        "",
    ]
    if deltas:
        for name, d in deltas[:8]:
            arrow = "📈" if d > 0 else "📉"
            lines.append(f"- {arrow} `{name}` {d:+}")
    else:
        lines.append("_No fitness movement this week (stable population)._")

    # lineage events of the week
    lin = darwin._load_json(darwin.LINEAGE_FILE, {"events": []})
    week_events = [e for e in lin["events"]
                   if datetime.fromisoformat(e["when"]) >= week_ago]
    lines += ["", "## Evolution events (7 days)", ""]
    if week_events:
        for e in week_events[-15:]:
            icon = {"mutation": "🧬", "crossover": "💞",
                    "trial_win": "🏆", "speciation": "🌍"}.get(
                        e.get("kind", ""), "•")
            lines.append(f"- {icon} {e.get('kind')}: `{e.get('parent')}` "
                         f"-> `{e.get('child')}`")
    else:
        lines.append("_None._")

    lines += ["", "---",
              "*Auto-generated by the Darwin Engine - the skill population "
              "evolves itself.*"]
    return "\n".join(lines)


def main():
    report = build_weekly()
    WEEKLY_FILE.parent.mkdir(parents=True, exist_ok=True)
    WEEKLY_FILE.write_text(report, encoding="utf-8")
    print(f"weekly report -> {WEEKLY_FILE}")
    if "--post" in sys.argv:
        r = subprocess.run(
            ["gh", "issue", "create",
             "--repo", "openamer/openamer",
             "--title", f"🧬 Darwin Weekly Report - "
                        f"{datetime.now(timezone.utc).strftime('%Y-%W')}",
             "--body-file", str(WEEKLY_FILE)],
            capture_output=True, text=True, cwd=str(REPO))
        if r.returncode == 0:
            print(f"posted: {r.stdout.strip()}")
        else:
            print(f"gh failed: {r.stderr.strip()[:200]}")
            sys.exit(1)


if __name__ == "__main__":
    main()
