"""OpenAmer Wiki Generator — Auto-Docs aus Skills + Code

Generiert eine vollständige Wissensdatenbank auf GitHub Pages.
Läuft als Cron-Job: aktualisiert die Docs täglich.
"""
import os, json, yaml, re
from pathlib import Path
from datetime import datetime

SKILLS_DIR = Path(os.path.expanduser("~")) / "AppData" / "Local" / "openamer-laptop" / "skills"
REPO_DOCS = Path(r"C:\Users\damir\openamer-repo\docs")
OUTPUT = REPO_DOCS / "wiki"

SKILL_ICONS = {
    "devops": "⚙️", "software-development": "💻", "autonomous-ai-agents": "🤖",
    "system": "🖥️", "productivity": "📋", "research": "🔬", "media": "🎬",
    "marketing": "📢", "security": "🔒", "email": "📧", "github": "🐙",
    "note-taking": "📝", "smart-home": "🏠", "desktop": "🖥️",
}

def extract_frontmatter(content: str) -> dict:
    """Extract YAML frontmatter from SKILL.md."""
    meta = {}
    if content.startswith('---'):
        parts = content.split('---', 2)
        if len(parts) >= 3:
            try:
                meta = yaml.safe_load(parts[1]) or {}
            except:
                pass
    return meta

def get_first_heading(content: str) -> str:
    """Get the first h1/h2 heading."""
    for line in content.split('\n'):
        line = line.strip()
        if line.startswith('# ') or line.startswith('## '):
            return line.lstrip('#').strip()
    return ""

def count_code_lines(content: str) -> int:
    lines = content.split('\n')
    code_lines = 0
    in_code = False
    for l in lines:
        if l.strip().startswith('```'):
            in_code = not in_code
            continue
        if in_code:
            code_lines += 1
    return code_lines

def generate_wiki():
    """Generate the full Wiki from all skills."""
    print(f"🔍 Scanning skills in: {SKILLS_DIR}")
    
    categories = {}
    total_skills = 0
    
    # Collect all skills by category
    for category_dir in SKILLS_DIR.iterdir():
        if not category_dir.is_dir():
            continue
        cat_name = category_dir.name
        icon = SKILL_ICONS.get(cat_name, "📦")
        
        skills = []
        for skill_dir in category_dir.iterdir():
            if not skill_dir.is_dir():
                continue
            skill_md = skill_dir / "SKILL.md"
            if not skill_md.exists():
                continue
            
            content = skill_md.read_text(encoding='utf-8', errors='replace')
            meta = extract_frontmatter(content)
            heading = meta.get('name', skill_dir.name)
            desc = meta.get('description', '')
            code_lines = count_code_lines(content)
            line_count = len(content.split('\n'))
            
            skills.append({
                "name": heading,
                "dir": skill_dir.name,
                "description": desc,
                "lines": line_count,
                "code_lines": code_lines,
                "content": content[:200] + "..." if len(content) > 200 else content,
            })
            total_skills += 1
        
        if skills:
            categories[cat_name] = {"icon": icon, "skills": skills}
    
    # Create output dir
    os.makedirs(OUTPUT, exist_ok=True)
    
    # Generate INDEX
    index_lines = [
        "---",
        "layout: page",
        "title: OpenAmer Wiki — Knowledge Base",
        "---",
        "",
        "# 🧠 OpenAmer Wiki",
        "",
        f"*Autogenerated: {datetime.now().strftime('%Y-%m-%d %H:%M')} — {total_skills} skills across {len(categories)} categories*",
        "",
        "## 📂 Categories",
        "",
    ]
    
    for cat_name, cat_data in sorted(categories.items()):
        n = len(cat_data["skills"])
        icon = cat_data["icon"]
        index_lines.append(f"- {icon} **{cat_name}** — {n} skills")
    
    index_lines.extend(["", "---", "", "## 📖 All Skills", ""])
    
    for cat_name, cat_data in sorted(categories.items()):
        icon = cat_data["icon"]
        index_lines.append(f"### {icon} {cat_name}")
        for s in sorted(cat_data["skills"], key=lambda x: x["name"]):
            desc = s["description"][:80] + "..." if len(s["description"]) > 80 else s["description"]
            index_lines.append(f"- **[{s['name']}]({cat_name}/{s['dir']}/)** — {desc}")
        index_lines.append("")
    
    with open(OUTPUT / "index.md", "w", encoding='utf-8') as f:
        f.write('\n'.join(index_lines))
    print(f"✅ Wiki Index: {total_skills} skills")
    
    # Generate per-category pages
    for cat_name, cat_data in categories.items():
        cat_dir = OUTPUT / cat_name
        os.makedirs(cat_dir, exist_ok=True)
        
        cat_lines = [
            "---",
            f"title: {cat_name}",
            "---",
            "",
            f"# {cat_data['icon']} {cat_name}",
            "",
            f"{len(cat_data['skills'])} skills",
            "",
        ]
        
        for s in sorted(cat_data["skills"], key=lambda x: x["name"]):
            sd = cat_dir / s["dir"]
            os.makedirs(sd, exist_ok=True)
            
            # Skill detail page
            detail = [
                "---",
                f"title: {s['name']}",
                f"description: {s['description'][:120]}",
                "---",
                "",
                f"# {s['name']}",
                "",
                f"**Description:** {s['description']}",
                f"**Lines:** {s['lines']} | **Code:** {s['code_lines']} | **Dir:** `{s['dir']}`",
                "",
                "---",
                "",
                s["content"],
            ]
            with open(sd / "index.md", "w", encoding='utf-8') as f:
                f.write('\n'.join(detail))
            
            cat_lines.append(f"- [{s['name']}]({s['dir']}/) — {s['description'][:80]}")
        
        cat_lines.append("")
        with open(cat_dir / "index.md", "w", encoding='utf-8') as f:
            f.write('\n'.join(cat_lines))
        
        print(f"  ✅ {cat_name}: {len(cat_data['skills'])} skills")
    
    # Generate STATS
    stats = {
        "total_skills": total_skills,
        "categories": len(categories),
        "generated": datetime.now().isoformat(),
        "repos": str(REPO_DOCS),
        "per_category": {c: len(d["skills"]) for c, d in categories.items()},
    }
    with open(OUTPUT / "stats.json", "w") as f:
        json.dump(stats, f, indent=2)
    print(f"\n✅ Wiki complete: {OUTPUT}")

if __name__ == "__main__":
    generate_wiki()